services:
  - type: web
    name: hospital
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheck:
      path: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString

databases:
  - name: hospital-db
    region: oregon
    plan: free
